### ISSUE TITLE
DEV Env: V5 to V3 backward compatibility not working when a member adds or removes a group

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/legacy-groups-processor#19]
V5 to V3 backward compatibility not working when a member is added or removed from a group on dev env.

This works fine in prod env.

Scenario: 

1.Update the user's groups in the profile settings page (groups v5)
https://www.topcoder-dev.com/settings/profile#communities
2.Verify the User's groups in dashboard page (groups v3)
https://www.topcoder-dev.com/my-dashboard
Or verify if Join button is visible/hidden on community home page (groups v3)
https://community-app.topcoder-dev.com/__community__/cognitive
3. Changes made in step 1 are not reflected in step 2

Note: The same scenario works fine in production

cc @dushyantb

**Comment by lakshmiathreya** [comment]
cc @wdprice

**Comment by wdprice** [comment]
@lakshmiathreya - this seems like a significant issue from my understanding of it. I wouldn't want to move Groups into prod while this is active. While the changes are needed for the skill search app (ubahn), I feel like this could affect other applications.

@dushyantb - cant you investigate?

 cc: @cwdcwd

**Comment by bountyC0d3r** [comment]
@wdprice @SathyaJayabal I'm getting issue in traits, while updating communities on `dev`

This has nothing to do with the `groups-api` or `groups-processor`; can we have first this `trait` issue fixed and then have it tested again?


<img width="1680" alt="Screenshot 2020-08-11 at 11 21 16 AM" src="https://user-images.githubusercontent.com/1861713/89862061-cb5a7f00-dbc4-11ea-8d3a-30a5eb0bfc5b.png">

**Comment by SathyaJayabal** [comment]
@dushyantb , please test with postman. cc @lakshmiathreya 

Update v5 groups in dev, check in v3 groups, you must see the update (actual: you don't see the update)
Update v5 groups in prod. Changes will be seen in V3 groups

The traits error sometimes happens in the FE (intermittent issue), but its not what this issue is about.

**Comment by SathyaJayabal** [comment]
@dushyantb @lakshmiathreya , here are videos for better representation of the issue
[groups_dev.mp4.zip](https://github.com/topcoder-platform/legacy-groups-processor/files/5055175/groups_dev.mp4.zip)
[groups_prod.mp4.zip](https://github.com/topcoder-platform/legacy-groups-processor/files/5055177/groups_prod.mp4.zip)

**Comment by bountyC0d3r** [comment]
@lakshmiathreya <https://github.com/lakshmiathreya> can you share those
videos?

Thanks & Regards,
Dushyant Bhalgami
+91 70309 99448

**Comment by bountyC0d3r** [comment]
@wdprice this has been fixed and ready for test on `dev`

**Comment by SathyaJayabal** [comment]
works as expected on dev

**Comment by wdprice** [comment]
Added label per discussion w @lakshmiathreya
